# Generated by Django 5.2.5 on 2025-08-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_customer_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='apis.line'),
        ),
    ]
