# Generated by Django 5.2.5 on 2025-08-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_expense_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('staff', 'Staff'), ('superadmin', 'Superadmin')], default='agent', max_length=20),
        ),
    ]
