# Generated by Django 5.2.5 on 2025-08-23 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_remove_payment_id_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.area'),
        ),
    ]
