# Generated by Django 5.2.5 on 2025-08-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_loan_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amt_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
