# Generated by Django 5.2.5 on 2025-08-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_payment_amt_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_loan', to='apis.loan'),
        ),
    ]
