# Generated by Django 5.2.5 on 2025-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_customuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_area_per_user'),
        ),
    ]
